name: CD Dev

on:
  push:
    branches: [main]

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup kubectl
        uses: azure/setup-kubectl@v4

      - name: Setup Helm
        uses: azure/setup-helm@v4

      # AWS EKS auth via OIDC (requires repo secrets):
      # - AWS_OIDC_ROLE_ARN_DEV: Role ARN with EKS + deploy permissions
      # - AWS_REGION: AWS region of your EKS cluster
      # - EKS_CLUSTER_DEV: EKS cluster name
      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE_ARN_DEV }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Update kubeconfig for EKS (dev)
        run: |
          aws eks update-kubeconfig --name "${{ secrets.EKS_CLUSTER_DEV }}" --region "${{ secrets.AWS_REGION }}"

      - name: Helm upgrade (dev)
        run: |
          helm upgrade --install liquid-hive helm/liquid-hive \
            -n liquid-hive-dev --create-namespace \
            -f helm/liquid-hive/values.yaml \
            -f helm/liquid-hive/values-dev.yaml \
            --set image.repository=ghcr.io/${{ github.repository_owner }}/liquid-hive \
            --set image.tag=${{ github.sha }}
