name: CD Prod

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup kubectl
        uses: azure/setup-kubectl@v4

      - name: Setup Helm
        uses: azure/setup-helm@v4

      # AWS EKS auth via OIDC (requires repo secrets):
      # - AWS_OIDC_ROLE_ARN_PROD: Role ARN with EKS + deploy permissions
      # - AWS_REGION: AWS region of your EKS cluster
      # - EKS_CLUSTER_PROD: EKS cluster name
      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE_ARN_PROD }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Update kubeconfig for EKS (prod)
        run: |
          aws eks update-kubeconfig --name "${{ secrets.EKS_CLUSTER_PROD }}" --region "${{ secrets.AWS_REGION }}"

      - name: Helm upgrade (prod)
        run: |
          helm upgrade --install liquid-hive infra/helm/liquid-hive \
            -n liquid-hive-prod --create-namespace \
            -f infra/helm/liquid-hive/values.yaml \
            -f infra/helm/liquid-hive/values-aws-prod.yaml \
            --set image.repository=ghcr.io/${{ github.repository_owner }}/liquid-hive \
            --set image.tag=${{ github.ref_name }}
