version: '3.9'
services:
  redis:
    image: redis:7-alpine
    container_name: lh_redis
    ports:
      - "6379:6379"
  qdrant:
    image: qdrant/qdrant:latest
    container_name: lh_qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
  minio:
    image: minio/minio:latest
    container_name: lh_minio
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minio123
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
