version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "03:00"
      timezone: "UTC"
    target-branch: "main"
    open-pull-requests-limit: 5
    labels: ["dependencies", "github-actions"]
    commit-message:
      prefix: "deps"
      include: "scope"
    groups:
      minor-and-patch:
        update-types: ["minor", "patch"]

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "03:10"
      timezone: "UTC"
    target-branch: "main"
    open-pull-requests-limit: 5
    labels: ["dependencies", "python"]
    commit-message:
      prefix: "deps"
      include: "scope"
    groups:
      minor-and-patch:
        update-types: ["minor", "patch"]

  - package-ecosystem: "pip"
    directory: "/src/internet_agent_advanced"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "03:15"
      timezone: "UTC"
    target-branch: "main"
    open-pull-requests-limit: 5
    labels: ["dependencies", "python"]
    commit-message:
      prefix: "deps"
      include: "scope"
    groups:
      minor-and-patch:
        update-types: ["minor", "patch"]

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "03:20"
      timezone: "UTC"
    target-branch: "main"
    open-pull-requests-limit: 5
    labels: ["dependencies", "javascript"]
    commit-message:
      prefix: "deps"
      include: "scope"
    groups:
      minor-and-patch:
        update-types: ["minor", "patch"]

  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "03:20"
      timezone: "UTC"
    target-branch: "main"
    open-pull-requests-limit: 5
    labels: ["dependencies", "javascript"]
    commit-message:
      prefix: "deps"
      include: "scope"
    versioning-strategy: "increase"
    groups:
      minor-and-patch:
        update-types: ["minor", "patch"]
      react-ecosystem:
        patterns: ["react*", "@types/react*"]
      testing-tools:
        patterns: ["@testing-library/*", "jest*", "@types/jest"]
      build-tools:
        patterns: ["vite*", "@vitejs/*", "typescript", "eslint*", "@typescript-eslint/*"]

  - package-ecosystem: "npm"
    directory: "/sdks/js"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "03:25"
      timezone: "UTC"
    target-branch: "main"
    open-pull-requests-limit: 5
    labels: ["dependencies", "javascript"]
    commit-message:
      prefix: "deps"
      include: "scope"
    groups:
      minor-and-patch:
        update-types: ["minor", "patch"]

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "03:30"
      timezone: "UTC"
    target-branch: "main"
    open-pull-requests-limit: 5
    labels: ["dependencies", "docker"]
    commit-message:
      prefix: "deps"
      include: "scope"
    groups:
      digest-minor-patch:
        update-types: ["digest", "minor", "patch"]
    ignore:
      - dependency-name: "torch"
      - dependency-name: "numpy"
    groups:
      ml-dependencies:
        patterns:
          - "torch*"
          - "transformers*"
          - "sentence-transformers*"
          - "faiss-*"
      dev-dependencies:
        patterns:
          - "pytest*"
          - "ruff"
          - "mypy"
          - "black"
          - "isort"
          - "bandit"
