version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:

      interval: "daily"
    open-pull-requests-limit: 5

  - package-ecosystem: "pip"

      interval: "weekly"
      day: "sunday"
      time: "03:00"
      timezone: "UTC"
    target-branch: "main"
    open-pull-requests-limit: 5
    labels: ["dependencies", "github-actions"]
    commit-message:
      prefix: "deps"
      include: "scope"
    groups:
      minor-and-patch:
        update-types: ["minor", "patch"]

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "03:10"
      timezone: "UTC"
    target-branch: "main"
    open-pull-requests-limit: 5
    labels: ["dependencies", "python"]
    commit-message:
      prefix: "deps"
      include: "scope"
    groups:
      minor-and-patch:
        update-types: ["minor", "patch"]

  - package-ecosystem: "npm"
        main
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    allow:
      - dependency-type: "all"

  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"

    open-pull-requests-limit: 5
    allow:
      - dependency-type: "all"

  - package-ecosystem: "npm"
    directory: "/sdks/js"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3

      day: "sunday"
      time: "03:20"
      timezone: "UTC"
    target-branch: "main"
    open-pull-requests-limit: 5
    labels: ["dependencies", "javascript"]
    commit-message:
      prefix: "deps"
      include: "scope"
    versioning-strategy: "increase"
    groups:
      minor-and-patch:
        update-types: ["minor", "patch"]

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "03:30"
      timezone: "UTC"
    target-branch: "main"
    open-pull-requests-limit: 5
    labels: ["dependencies", "docker"]
    commit-message:
      prefix: "deps"
      include: "scope"
    groups:
      digest-minor-patch:
        update-types: ["digest", "minor", "patch"]
        main
