extends: default

rules:
  line-length:
    max: 120
    level: warning
  
  indentation:
    spaces: 2
    
  comments:
    min-spaces-from-content: 1
    
  document-start:
    present: false
    
  truthy:
    allowed-values: [true, false, yes, no]
    check-keys: true
    
  brackets:
    min-spaces-inside: 0
    max-spaces-inside: 1
    
  braces:
    min-spaces-inside: 0
    max-spaces-inside: 1
    
ignore: |
  frontend/node_modules/
  frontend/dist/
  .github/workflows/
  helm/
  k8s/
  prometheus/
  grafana/