services:
  api:
    build: ./apps/api
    env_file: .env
    ports: ["8080:8080"]
    depends_on: [prometheus]
  frontend:
    build: ./frontend
    environment:
      - VITE_API_BASE=${VITE_API_BASE:-http://localhost:8080}
    ports: ["5173:5173"]
    depends_on: [api]
  prometheus:
    image: prom/prometheus:latest
    volumes: ["./infra/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"]
    ports: ["9090:9090"]
  grafana:
    image: grafana/grafana:latest
    ports: ["3000:3000"]
    depends_on: [prometheus]
  # optional
  redis:
    image: redis:7
    ports: ["6379:6379"]
  qdrant:
    image: qdrant/qdrant:latest
    ports: ["6333:6333"]
