line-length = 100
target-version = "py311"

[lint]
select = [
    "E",  # pycodestyle errors
    "W",  # pycodestyle warnings
    "F",  # pyflakes
    "I",  # isort
    "B",  # flake8-bugbear
    "C4", # flake8-comprehensions
    "UP", # pyupgrade
]
ignore = [
    "E501",  # line too long, handled by formatter
    "B008",  # do not perform function calls in argument defaults
    "E402",  # module level import not at top of file (common in conditional imports)
    "F401",  # unused import (many are used conditionally)
    "B904",  # raise without from inside except (acceptable in many cases)
    "B005",  # strip with multi-characters (acceptable usage)
    "B007",  # unused loop control variable (acceptable when only value is needed)
]

[format]
quote-style = "double"
indent-style = "space"
