apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "liquid-hive-upgrade.fullname" . }}-config
  labels:
    {{- include "liquid-hive-upgrade.labels" . | nindent 4 }}
data:
  app-config.yaml: |
    # Application Configuration
    app:
      name: {{ .Chart.Name }}
      version: {{ .Chart.AppVersion }}
      environment: {{ .Values.env.ENVIRONMENT }}
    
    # Server Configuration
    server:
      host: {{ .Values.env.HOST }}
      port: {{ .Values.env.PORT }}
      workers: {{ .Values.env.WORKERS }}
      
    # Features
    features:
      planner: {{ .Values.env.ENABLE_PLANNER }}
      arena: {{ .Values.env.ENABLE_ARENA }}
      internet_agent: {{ .Values.env.ENABLE_INTERNET_AGENT }}
    
    # Rate Limiting
    rate_limiting:
      rps: {{ .Values.env.RATE_LIMIT_RPS }}
      burst: {{ .Values.env.RATE_LIMIT_BURST }}
    
    # Routing
    routing:
      profile: {{ .Values.env.ROUTING_PROFILE }}
    
    # Observability
    observability:
      otel:
        service_name: {{ .Values.env.OTEL_SERVICE_NAME }}
        service_version: {{ .Values.env.OTEL_SERVICE_VERSION }}
        endpoint: {{ .Values.env.OTEL_EXPORTER_OTLP_ENDPOINT }}
        sampler: {{ .Values.env.OTEL_TRACES_SAMPLER }}
      prometheus:
        enabled: {{ .Values.env.PROMETHEUS_ENABLED }}
      logging:
        level: {{ .Values.env.LOG_LEVEL }}
        format: {{ .Values.env.LOG_FORMAT }}
    
    # Tenancy
    tenancy:
      mode: {{ .Values.env.TENANCY_MODE }}
      max_tenants: {{ .Values.env.MAX_TENANTS }}