# Base configuration for Liquid Hive
app:
  name: "Liquid Hive"
  version: "1.0.0"
  debug: false
  environment: "production"

api:
  host: "0.0.0.0"
  port: 8000
  workers: 1
  reload: false
  log_level: "info"
  cors_origins: ["http://localhost:3000", "http://localhost:5173"]

database:
  url: "sqlite:///./liquid_hive.db"
  echo: false
  pool_size: 5
  max_overflow: 10
  pool_timeout: 30
  pool_recycle: 3600

redis:
  url: "redis://localhost:6379/0"
  max_connections: 10
  socket_timeout: 5
  socket_connect_timeout: 5
  retry_on_timeout: true

cache:
  default_ttl: 3600
  max_size: 1000
  cleanup_interval: 300

logging:
  level: "INFO"
  format: "json"
  handlers:
    - type: "console"
    - type: "file"
      filename: "logs/liquid_hive.log"
      max_bytes: 10485760
      backup_count: 5

monitoring:
  metrics_enabled: true
  health_check_interval: 30
  prometheus_port: 9090

security:
  secret_key: "change-me-in-production"
  access_token_expire_minutes: 30
  refresh_token_expire_days: 7
  algorithm: "HS256"
  password_min_length: 8
  max_login_attempts: 5
  lockout_duration_minutes: 15

features:
  rag_enabled: true
  agent_autonomy: true
  swarm_protocol: true
  safety_checks: true
  confidence_modeling: true