namespace: liquid-hive

global:
  otel:
    enabled: true
    endpoint: http://liquid-hive-otel-collector:4317
    serviceName: liquid-hive-unified-runtime
    sampleRatio: 0.1

unifiedRuntime:
  enabled: true
  replicas: 2
  image:
    repository: ghcr.io/OWNER/liquid-hive-unified-runtime
    tag: latest
    pullPolicy: IfNotPresent
  service:
    port: 8000
    metricsPort: 9090
  resources:
    requests:
      cpu: "250m"
      memory: "512Mi"
    limits:
      cpu: "1"
      memory: "1Gi"
  securityContext:
    runAsNonRoot: true
    runAsUser: 10001
    runAsGroup: 10001
    fsGroup: 10001
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    capabilities:
      drop: [ "ALL" ]
  env:
    - name: OTEL_EXPORTER_OTLP_ENDPOINT
      valueFrom:
        configMapKeyRef:
          name: liquid-hive-otel-config
          key: otlpEndpoint
    - name: OTEL_SERVICE_NAME
      value: liquid-hive-unified-runtime
    - name: OTEL_TRACES_SAMPLER_ARG
      value: "0.1"
  extraEnv: []
  extraVolumeMounts: []
  extraVolumes: []
  probes:
    path: /healthz
    startupSeconds: 5
    periodSeconds: 10
    timeoutSeconds: 2
    failureThreshold: 6
  hpa:
    enabled: true
    minReplicas: 2
    maxReplicas: 10
    targetCPUUtilizationPercentage: 70
    targetMemoryUtilizationPercentage: 80

rbac:
  create: true

externalSecrets:
  enabled: true
  secretStoreRef:
    kind: ClusterSecretStore
    name: external-secrets
  data:
    - secretKey: PROVIDER_API_KEYS
      remoteRef:
        key: liquid-hive/provider-api-keys

networkPolicy:
  enabled: true
  egress:
    - to:
        - namespaceSelector: {}
      ports:
        - port: 443
          protocol: TCP
        - port: 80
          protocol: TCP

otelCollector:
  enabled: true
  image: otel/opentelemetry-collector-contrib:0.101.0
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi
