{{- if and .Values.secrets.vault.enabled (eq .Values.secrets.provider "vault") }}
---
# Development Vault deployment - DO NOT USE IN PRODUCTION
# This is for local development only
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "liquid-hive.fullname" . }}-vault-dev
  labels:
    {{- include "liquid-hive.labels" . | nindent 4 }}
    component: vault-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "liquid-hive.selectorLabels" . | nindent 6 }}
      component: vault-dev
  template:
    metadata:
      labels:
        {{- include "liquid-hive.selectorLabels" . | nindent 8 }}
        component: vault-dev
    spec:
      containers:
        - name: vault
          image: vault:1.15
          args:
            - "vault"
            - "server"
            - "-dev"
            - "-dev-listen-address=0.0.0.0:8200"
            - "-dev-root-token-id=dev-token"
          ports:
            - containerPort: 8200
              name: vault
          env:
            - name: VAULT_DEV_ROOT_TOKEN_ID
              value: "dev-token"
            - name: VAULT_ADDR
              value: "http://0.0.0.0:8200"
          readinessProbe:
            httpGet:
              path: /v1/sys/health
              port: 8200
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /v1/sys/health
              port: 8200
              scheme: HTTP
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "liquid-hive.fullname" . }}-vault-dev
  labels:
    {{- include "liquid-hive.labels" . | nindent 4 }}
    component: vault-dev
spec:
  type: ClusterIP
  ports:
    - port: 8200
      targetPort: 8200
      name: vault
  selector:
    {{- include "liquid-hive.selectorLabels" . | nindent 4 }}
    component: vault-dev
{{- end }}