apiVersion: apps/v1
kind: Deployment
metadata:
  name: fusion-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fusion-app
  template:
    metadata:
      labels:
        app: fusion-app
    spec:
      containers:
        - name: api
          image: fusion:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: HOST
              value: "0.0.0.0"
            - name: PORT
              value: "8080"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: fusion-app
spec:
  selector:
    app: fusion-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP