name: 💡 Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a new feature! Please fill out this form to help us understand your request.

  - type: checkboxes
    attributes:
      label: Prerequisites
      description: Please confirm the following before submitting your feature request
      options:
        - label: I have searched existing issues to ensure this feature hasn't been requested
          required: true
        - label: I have read the contributing guidelines
          required: true
        - label: This feature aligns with the project's goals and scope
          required: true

  - type: textarea
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What need does it address?
      placeholder: Describe the problem or need this feature would address...
    validations:
      required: true

  - type: textarea
    attributes:
      label: Proposed Solution
      description: Describe your proposed solution or feature
      placeholder: Describe your proposed solution in detail...
    validations:
      required: true

  - type: textarea
    attributes:
      label: Alternative Solutions
      description: Describe any alternative solutions or features you've considered
      placeholder: What alternatives have you considered?

  - type: dropdown
    attributes:
      label: Component
      description: Which component would this feature affect?
      options:
        - Frontend (React/TypeScript)
        - Backend (FastAPI/Python)
        - Planner (DAG Execution)
        - Arena (Model Evaluation)
        - Oracle (LLM Providers)
        - Authentication/Security
        - Database (MongoDB/Redis/Neo4j)
        - Deployment (Docker/Kubernetes)
        - API/Integration
        - Documentation
        - Other
    validations:
      required: true

  - type: dropdown
    attributes:
      label: Feature Type
      description: What type of feature is this?
      options:
        - New functionality
        - Performance improvement
        - Developer experience
        - User interface enhancement
        - Integration/API
        - Security enhancement
        - Documentation
        - Testing
    validations:
      required: true

  - type: dropdown
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low (Nice to have)
        - Medium (Would improve workflow)
        - High (Important for my use case)
        - Critical (Blocking my adoption)
    validations:
      required: true

  - type: textarea
    attributes:
      label: Use Cases
      description: Describe specific use cases where this feature would be beneficial
      placeholder: |
        1. Use case 1: ...
        2. Use case 2: ...
    validations:
      required: true

  - type: textarea
    attributes:
      label: Success Criteria
      description: How would you measure the success of this feature?
      placeholder: What would indicate that this feature is working well?

  - type: textarea
    attributes:
      label: Technical Considerations
      description: Any technical considerations, constraints, or implementation ideas?
      placeholder: Technical details, API design, performance considerations, etc.

  - type: textarea
    attributes:
      label: Breaking Changes
      description: Would this feature introduce any breaking changes?
      placeholder: Describe any potential breaking changes or migration requirements

  - type: textarea
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or examples about the feature request
      placeholder: Screenshots, mockups, examples, links to similar features, etc.

  - type: checkboxes
    attributes:
      label: Willingness to Contribute
      description: Would you be willing to help implement this feature?
      options:
        - label: I would be willing to submit a pull request to implement this feature
        - label: I would be willing to help with testing this feature
        - label: I would be willing to help with documentation for this feature
