name: 🔒 Security Issue
description: Report a security vulnerability (Use only for non-sensitive issues)
title: "[Security]: "
labels: ["security", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        ⚠️ **IMPORTANT SECURITY NOTICE** ⚠️
        
        **DO NOT** use this form for reporting security vulnerabilities that could be exploited.
        
        For sensitive security issues, please email: **security@liquid-hive.dev**
        
        This form should only be used for:
        - Security hardening suggestions
        - Non-exploitable security improvements
        - Security documentation issues
        - General security questions

  - type: checkboxes
    attributes:
      label: Security Confirmation
      description: Please confirm this is not a sensitive security vulnerability
      options:
        - label: This is NOT a security vulnerability that could be exploited
          required: true
        - label: This is a general security improvement or hardening suggestion
          required: true
        - label: I understand that sensitive vulnerabilities should be reported to security@liquid-hive.dev
          required: true

  - type: dropdown
    attributes:
      label: Security Category
      description: What type of security issue is this?
      options:
        - Security hardening suggestion
        - Security documentation improvement
        - Security configuration question
        - Security best practices
        - Dependency security update
        - Security testing improvement
        - Other security enhancement
    validations:
      required: true

  - type: textarea
    attributes:
      label: Security Issue Description
      description: Describe the security concern or improvement
      placeholder: Describe the security issue or improvement suggestion...
    validations:
      required: true

  - type: textarea
    attributes:
      label: Current Security Posture
      description: How is this currently handled (if applicable)?
      placeholder: Current implementation or lack thereof...

  - type: textarea
    attributes:
      label: Recommended Improvement
      description: What specific security improvement do you recommend?
      placeholder: Detailed recommendation for improvement...
    validations:
      required: true

  - type: dropdown
    attributes:
      label: Component Affected
      description: Which component does this security issue affect?
      options:
        - Authentication/Authorization
        - API Security 
        - Database Security
        - Frontend Security
        - Container/Deployment Security
        - Network Security
        - Input Validation
        - Cryptography
        - Secrets Management
        - Logging/Monitoring
        - Dependencies
        - Configuration
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    attributes:
      label: Implementation Suggestions
      description: Any specific implementation suggestions or references?
      placeholder: Code examples, links to best practices, implementation ideas...

  - type: textarea
    attributes:
      label: Security Standards
      description: Does this relate to any specific security standards or compliance requirements?
      placeholder: OWASP, NIST, SOC2, GDPR, etc.

  - type: checkboxes
    attributes:
      label: Willingness to Contribute
      description: Would you be willing to help implement this security improvement?
      options:
        - label: I would be willing to submit a pull request for this security improvement
        - label: I would be willing to help with security testing
        - label: I would be willing to help with security documentation