{{- if .Values.namespaceCreate }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace }}
  labels:
    pod-security.kubernetes.io/enforce: restricted
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: liquid-hive-quota
  namespace: {{ .Values.namespace }}
spec:
  hard:
    pods: "100"
    requests.cpu: "10"
    requests.memory: 32Gi
    limits.cpu: "40"
    limits.memory: 64Gi
---
apiVersion: v1
kind: LimitRange
metadata:
  name: container-limits
  namespace: {{ .Values.namespace }}
spec:
  limits:
    - type: Container
      default:
        cpu: "1000m"
        memory: "1Gi"
      defaultRequest:
        cpu: "250m"
        memory: "512Mi"
{{- end }}
