{{- if .Values.otelCollector.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: liquid-hive-otel-collector-config
  namespace: {{ .Values.namespace }}
data:
  config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
    processors:
      batch:
    exporters:
      logging:
        loglevel: info
    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [logging]
        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters: [logging]
        logs:
          receivers: [otlp]
          processors: [batch]
          exporters: [logging]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: liquid-hive-otel-collector
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: liquid-hive-otel-collector
  template:
    metadata:
      labels:
        app: liquid-hive-otel-collector
    spec:
      securityContext:
        fsGroup: 10001
      containers:
        - name: otel-collector
          image: {{ .Values.otelCollector.image }}
          args: [ "--config=/etc/otel/config.yaml" ]
          ports:
            - containerPort: 4317
              name: otlp-grpc
            - containerPort: 4318
              name: otlp-http
          volumeMounts:
            - name: cfg
              mountPath: /etc/otel
          resources:
            {{- toYaml .Values.otelCollector.resources | nindent 12 }}
          securityContext:
            runAsNonRoot: true
            runAsUser: 10001
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: [ "ALL" ]
      volumes:
        - name: cfg
          configMap:
            name: liquid-hive-otel-collector-config
---
apiVersion: v1
kind: Service
metadata:
  name: liquid-hive-otel-collector
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: liquid-hive-otel-collector
  ports:
    - name: otlp-grpc
      port: 4317
      targetPort: otlp-grpc
    - name: otlp-http
      port: 4318
      targetPort: otlp-http
{{- end }}
