{{- if and .Values.unifiedRuntime.enabled .Values.monitoring.serviceMonitor.enabled (.Capabilities.APIVersions.Has "monitoring.coreos.com/v1") }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: liquid-hive-unified-runtime
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: unified-runtime
  endpoints:
    - port: metrics
      interval: {{ .Values.monitoring.serviceMonitor.interval | default "15s" }}
      path: {{ .Values.monitoring.serviceMonitor.path | default "/metrics" }}
{{- end }}
