# Development environment values
# Uses local Vault in development mode

replicaCount: 1

# Secrets Management - Local Vault
secrets:
  provider: "vault"
  vault:
    enabled: true
    address: "http://liquid-hive-vault-dev:8200"
    token: "dev-token"  # Only for development!
    mountPath: "secret"

# Development configuration
config:
  database:
    mongoUrl: "mongodb://mongo:27017/liquid-hive-dev"
    redisUrl: "redis://redis:6379"
    neo4jUrl: "bolt://neo4j:7687"
    # Optional integrations (uncomment to enable)
    # qdrantUrl: "http://qdrant:6333"
    # minioEndpoint: "http://minio:9000"
    # minioAccessKey: "minio"
    # minioSecretKey: "minio123"
    # minioBucket: "web-raw"
    # minioSecure: false
  ai:
    vllmEndpoint: "http://vllm:8000"
    vllmApiKey: "dev-key"
  monitoring:
    prometheusBaseUrl: "http://prometheus:9090"
  features:
    modelRoutingEnabled: false
    trustedAutonomyEnabled: false
    autoPromoteEnabled: false

# Reduced resources for development
resources:
  limits:
    cpu: 1000m
    memory: 2Gi
  requests:
    cpu: 250m
    memory: 512Mi

# Development storage
storage:
  enabled: true
  size: 5Gi