apiVersion: v1
kind: Secret
metadata:
  name: liquid-hive-runtime-secrets
  namespace: liquid-hive-dev
type: Opaque
stringData:
  # Example keys; this file is intended to be encrypted with SOPS (see sops.yaml)
  OPENAI_API_KEY: placeholder
  DEEPSEEK_API_KEY: placeholder
  DEEPSEEK_R1_API_KEY: placeholder
  ANTHROPIC_API_KEY: placeholder
  QWEN_API_KEY: placeholder
  ADMIN_TOKEN: placeholder
  OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4317
