{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "liquid-hive.fullname" . }}-app-secrets
  labels:
    {{- include "liquid-hive.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval | default "1h" }}
  secretStoreRef:
    kind: {{ .Values.externalSecrets.secretStore.kind | default "ClusterSecretStore" }}
    name: {{ .Values.externalSecrets.secretStore.name }}
  target:
    name: {{ include "liquid-hive.fullname" . }}-runtime-secrets
    creationPolicy: Owner
  data:
    {{- range $k, $v := .Values.externalSecrets.data }}
    - secretKey: {{ $k }}
      remoteRef:
        key: {{ $v.key }}
        {{- if $v.property }}
        property: {{ $v.property }}
        {{- end }}
    {{- end }}
{{- end }}
