apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "liquid-hive.fullname" . }}-config
  labels:
    {{- include "liquid-hive.labels" . | nindent 4 }}
data:
  {{- if .Values.config.database.mongoUrl }}
  mongo_url: {{ .Values.config.database.mongoUrl | quote }}
  {{- end }}
  {{- if .Values.config.database.redisUrl }}
  redis_url: {{ .Values.config.database.redisUrl | quote }}
  {{- end }}
  {{- if .Values.config.database.neo4jUrl }}
  neo4j_url: {{ .Values.config.database.neo4jUrl | quote }}
  {{- end }}
  {{- if .Values.config.ai.vllmEndpoint }}
  vllm_endpoint: {{ .Values.config.ai.vllmEndpoint | quote }}
  {{- end }}
  {{- if .Values.config.ai.vllmEndpointSmall }}
  vllm_endpoint_small: {{ .Values.config.ai.vllmEndpointSmall | quote }}
  {{- end }}
  {{- if .Values.config.ai.vllmEndpointLarge }}
  vllm_endpoint_large: {{ .Values.config.ai.vllmEndpointLarge | quote }}
  {{- end }}
  {{- if .Values.config.monitoring.prometheusBaseUrl }}
  prometheus_base_url: {{ .Values.config.monitoring.prometheusBaseUrl | quote }}
  {{- end }}