name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Test API imports
        run: |
          python -c "import apps.api.main; print('API imports successfully')"
          
      - name: Test API endpoints
        run: |
          python -c "
          from fastapi.testclient import TestClient
          from apps.api.main import app
          client = TestClient(app)
          response = client.get('/healthz')
          assert response.status_code == 200
          print('API endpoints working')
          "
