name: CI
on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:7-alpine
        ports: ['6379:6379']
      neo4j:
        image: neo4j:5.15
        env:
          NEO4J_AUTH: 'neo4j/test_password'
        ports: ['7687:7687']
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install httpx pytest-asyncio
      - name: Run unit tests (planner + arena)
        env:
          ENABLE_ARENA: 'true'
          REDIS_URL: 'redis://localhost:6379/0'
          NEO4J_URI: 'bolt://localhost:7687'
          NEO4J_USER: 'neo4j'
          NEO4J_PASSWORD: 'test_password'
        run: |
          pytest -q tests/test_planner.py tests/test_arena.py
      - name: Export OpenAPI
        run: |
          python scripts/export_openapi.py
      - name: Upload OpenAPI
        uses: actions/upload-artifact@v4
        with:
          name: openapi
          path: docs/openapi.json