name: Manual Deploy
on:
  workflow_dispatch:
    inputs:
      host:
        description: "SSH host (user@host)"
        required: true
      path:
        description: "Deploy path on host"
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy over SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ inputs.host }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            set -e
            mkdir -p ${{ inputs.path }}
            rsync -a --delete . ${{ secrets.DEPLOY_USER }}@${{ inputs.host }}:${{ inputs.path }}
            cd ${{ inputs.path }}
            docker compose pull || true
            docker compose up -d --build
