name: Manual Deploy
on:
  workflow_dispatch:
    inputs:
      host:
        description: "SSH host (user@host)"
        required: true
      path:
        description: "Deploy path on host"
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Create deployment archive
        run: |
          tar -czf deployment.tar.gz --exclude='.git' --exclude='node_modules' --exclude='__pycache__' .
      
      - name: Copy files to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ github.event.inputs.host }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          source: "deployment.tar.gz"
          target: "/tmp/"
      
      - name: Deploy over SSH
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ github.event.inputs.host }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            set -e
            mkdir -p ${{ github.event.inputs.path }}
            cd ${{ github.event.inputs.path }}
            tar -xzf /tmp/deployment.tar.gz
            rm /tmp/deployment.tar.gz
            docker compose pull || true
            docker compose up -d --build
