name: Frontend CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'
          cache-dependency-path: frontend/yarn.lock
      - name: Install dependencies
        run: |
          cd frontend
          yarn install --frozen-lockfile
      - name: Type check
        run: |
          cd frontend
          yarn type-check
      - name: Lint
        run: |
          cd frontend
          yarn lint
      - name: Build
        run: |
          cd frontend
          yarn build
      - name: Test
        run: |
          cd frontend
          yarn test --coverage --watchAll=false
