name: Python CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install
        run: |
          pip install --upgrade pip
          pip install -e .[dev] || pip install -r requirements.txt
      - name: Lint & Typecheck
        run: |
          pip install ruff black mypy
          ruff check .
          black --check .
          mypy src || true
      - name: Tests
        run: |
          pip install pytest pytest-cov
          pytest -q --disable-warnings --maxfail=1 --cov=src
