name: Security Scan
on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  trivy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Trivy FS scan
        uses: aquasecurity/trivy-action@0.20.0
        with:
          scan-type: 'fs'
          format: 'table'
          exit-code: '0'
          ignore-unfixed: true
      - name: Run Trivy config scan
        uses: aquasecurity/trivy-action@0.20.0
        with:
          scan-type: 'config'
          format: 'table'
          exit-code: '1'
          hide-progress: true