name: Supply Chain Security

on:
  workflow_dispatch:
    inputs:
      image_repository:
        description: "Container image repository"
        required: true
        default: ghcr.io/your-org/liquid-hive
      image_tag:
        description: "Image tag"
        required: true
        default: latest

jobs:
  deps-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install pip-audit
        run: |
          python -m pip install --upgrade pip
          pip install pip-audit
      - name: Audit backend deps
        run: pip-audit -r backend/requirements.txt || true

  image-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    steps:
      - name: Install Trivy
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: image
          image-ref: ${{ github.event.inputs.image_repository }}:${{ github.event.inputs.image_tag }}
          format: table
          exit-code: "0"
          ignore-unfixed: true
