# Production environment overrides
app:
  debug: false
  environment: "production"

api:
  workers: 4
  reload: false
  log_level: "warning"

database:
  echo: false
  pool_size: 20
  max_overflow: 30

redis:
  max_connections: 50

cache:
  default_ttl: 7200
  max_size: 10000

logging:
  level: "WARNING"
  format: "json"

monitoring:
  metrics_enabled: true
  health_check_interval: 10

security:
  # These should be set via environment variables in production
  secret_key: "${SECRET_KEY}"
  access_token_expire_minutes: 15
  refresh_token_expire_days: 1
  password_min_length: 12
  max_login_attempts: 3
  lockout_duration_minutes: 30

features:
  debug_mode: false
  mock_external_services: false